{
  "family": "hello-world",
  "networkMode": "awsvpc",
  "containerDefinitions": [
    {
      "name": "hello-world",
      "image": "ECR_REGISTRY/hello-world:IMAGE_TAG",
      "essential": true,
      "portMappings": [
        {
          "containerPort": 80,
          "hostPort": 80
        }
      ]
    }
  ],
  "requiresCompatibilities": ["FARGATE"],
  "cpu": "256",
  "memory": "512"
}
